version: '3.3'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - .certbot/etc:/etc/letsencrypt
      - .certbot/var:/var/lib/letsencrypt
      - .certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email {email} --keep-until-expiring -d {domain} --agree-tos
  nginx:
    stdin_open: true
    image: nginx
    restart: unless_stopped
    container_name: nginx_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .certbot/etc:/etc/letsencrypt
      - .certbot/var:/var/lib/letsencrypt
      - .certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443