version: '3.3'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - .certbot/etc:/etc/letsencrypt
      - .certbot/var:/var/lib/letsencrypt
      - .certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email {email} --keep-until-expiring -d {domain} --agree-tos