version: '3.3'

services:
  nginx:
    stdin_open: true
    depends_on:
      - api
    image: nginx
    restart: unless-stopped
    container_name: nginx_server
    volumes:
      - ./nginx/temp-nginx.conf:/etc/nginx/conf.d/default.conf
      - .certbot/etc:/etc/letsencrypt
      - .certbot/var:/var/lib/letsencrypt
      - .certbot/www:/var/www/certbot
    ports:
      - 80:80
    networks:
      - app_network
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: node_app
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules
      - ./:/app/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
